# Generated by Django 3.0 on 2020-04-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Today', max_length=2550),
            preserve_default=False,
        ),
    ]
