# Generated by Django 3.0 on 2020-04-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200415_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.CharField(default='200,000', max_length=50),
            preserve_default=False,
        ),
    ]
