# Generated by Django 3.0.5 on 2020-04-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_delete_customerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
            ],
        ),
    ]
