# Generated by Django 3.0.5 on 2020-04-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default='10000'),
            preserve_default=False,
        ),
    ]
