# Generated by Django 3.0.5 on 2020-04-26 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactMessage',
        ),
    ]
