# Generated by Django 3.0.5 on 2020-04-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20200426_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='delivery',
            field=models.CharField(default='lorem', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='specification',
            field=models.TextField(default='lorem', max_length=2550),
            preserve_default=False,
        ),
    ]
