# Generated by Django 3.0.5 on 2020-04-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20200426_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='delivery',
        ),
    ]
