# Generated by Django 3.0.5 on 2020-05-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_remove_item_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
