# Generated by Django 3.0.5 on 2020-05-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20200509_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='phone',
            field=models.CharField(default='098765', max_length=50),
            preserve_default=False,
        ),
    ]
