# Generated by Django 3.0.5 on 2020-05-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_billingaddress_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='charge_id',
            new_name='reference',
        ),
    ]
