# Generated by Django 3.0.5 on 2020-05-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_auto_20200516_2222'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('title', 'slug')},
        ),
    ]
